import Link from "next/link";
import { getLocale } from "@/lib/locale";
import { getMessages, translator } from "@/lib/i18n";
import { demoReport } from "@/lib/report/demo";
import { ReportExperience } from "@/components/experience/ReportExperience";
import { LetterJourney } from "@/components/experience/LetterJourney";
import { EmptyState } from "@/components/experience/EmptyState";
import { ScoreRing } from "@/components/experience/ScoreRing";
import { VigilCalendar } from "@/components/VigilCalendar";
import { GuideChecklist } from "@/components/GuideChecklist";
import { LocaleSwitcher } from "@/components/LocaleSwitcher";

export const metadata = { title: "Rastro · Demo", robots: { index: false, follow: false } };
const SCREENS = ["report", "dashboard", "letter", "profile", "team", "guardian", "system"] as const;

export default async function DemoPage({ searchParams }: { searchParams: Promise<{ screen?: string }> }) {
  const locale = await getLocale(); const messages = getMessages(locale); const tr = translator(messages);
  const query = await searchParams;
  const screen = SCREENS.find((s) => s === query.screen) ?? "report";
  const report = demoReport(locale);
  const titleKey = (s: string) => `experience.demo${s.charAt(0).toUpperCase()}${s.slice(1)}`;
  return <>
    <header className="ex-demo-banner"><div><span className="ex-eyebrow">{tr("experience.demoBadge")}</span><p>{tr("experience.demoBody")}</p></div><div className="ex-actions"><Link className="ex-button-secondary" href="/#form">{tr("experience.demoStart")} ↗</Link><LocaleSwitcher current={locale} messages={messages}/></div></header>
    <main className="ex-page"><nav className="ex-demo-nav" aria-label={tr("experience.demoNav")}>{SCREENS.map((s) => <Link key={s} href={`/demo?screen=${s}`} aria-current={screen === s ? "page" : undefined}>{tr(titleKey(s))}</Link>)}</nav>
      {screen === "report" && <ReportExperience report={report} requestId={`demo-${locale}`} fullName={tr("experience.demoName")} messages={messages} locale={locale} demo/>}
      {screen === "dashboard" && <div className="grid gap-5"><div className="ex-page-heading"><div><p className="ex-eyebrow">{tr("experience.label")}</p><h1>{tr("experience.dashboardTitle")}</h1><p>{tr("experience.dashboardBody")}</p></div></div><section className="ex-report-hero"><div className="ex-hero-text"><span className="ex-badge"><span className="ex-dot"/>{tr("experience.active")}</span><h2>{tr("dash.hello", { name: tr("experience.demoName") })}</h2><p className="ex-hero-summary">{report.summary}</p><Link className="ex-button" href="/demo?screen=report">{tr("experience.viewReport")} ↗</Link></div><div className="ex-hero-score"><ScoreRing score={report.score} label={tr("experience.score")}/><span className="ex-badge">+8 · {tr("dash.historyTitle")}</span></div></section><div className="ex-two-col"><section className="ex-panel"><h2 className="mb-3 text-lg font-medium">{tr("experience.missions")}</h2><p className="ex-note mb-5">{tr("experience.missionHint")}</p><GuideChecklist reportId={`demo-${locale}`} items={report.actions} doneTemplate={tr("dash.guideDone")}/></section><section className="ex-panel"><h2 className="mb-6 text-lg font-medium">{tr("dash.historyTitle")}</h2><div className="flex h-44 items-end justify-around gap-4" role="img" aria-label="54 → 58 → 62 / 100">{[54,58,62].map((score,i) => <div key={score} className="flex h-full flex-col items-center justify-end gap-3 text-xs text-muted"><span>{score}</span><div className="w-10 rounded-t-lg bg-accent" style={{height:`${score}%`}}/><span>{["07","08","09"][i]} / 2026</span></div>)}</div><Link className="ex-text-link mt-8" href="/demo?screen=profile">{tr("experience.demoProfile")} ↗</Link></section></div></div>}
      {screen === "letter" && <div className="grid gap-5"><div className="ex-page-heading"><div><p className="ex-eyebrow">{tr("letters.title")}</p><h1>{tr("experience.letterJourney")}</h1><p>{tr("experience.letterDemoHint")}</p></div></div><LetterJourney messages={messages} locale={locale} events={[{ type:"sent_by_rastro",at:"2026-08-20T10:00:00Z",to:"privacy@example.org" },{type:"follow_up",at:"2026-09-09T10:00:00Z"},{type:"answered",at:"2026-09-14T14:00:00Z"}]} checkedAt="2026-09-16T09:30:00Z" stillListed={false}/></div>}
      {screen === "profile" && <div className="grid gap-5"><div className="ex-page-heading"><div><p className="ex-eyebrow">{tr("experience.demoProfile")}</p><h1>{tr("experience.active")}</h1><p>{tr("monitor.body")}</p></div></div><VigilCalendar locale={locale} messages={messages} monitoring consentAt="2026-08-20T10:00:00Z" lastAt="2026-09-01T10:00:00Z" checks={["2026-09-01T10:00:00Z"]} daily={["10","11","12","13","14","15","16"].map((d) => ({day:`2026-09-${d}`,status:"ok" as const}))} justEnabled={false}/></div>}
      {screen === "team" && <div className="grid gap-5"><div className="ex-page-heading"><div><p className="ex-eyebrow">Rastro Equipos</p><h1>{tr("experience.teamPrivacy")}</h1><p>{tr("experience.teamPrivacyBody")}</p></div></div><div className="ex-stat-grid"><div className="ex-stat"><strong>74</strong><span>{tr("experience.teamAverage")}</span></div><div className="ex-stat"><strong>03 / 05</strong><span>{tr("experience.teamOpted")}</span></div></div><section className="ex-panel"><table className="ex-team-table"><thead><tr><th>{tr("team.eyebrow")}</th><th>{tr("experience.teamStatus")}</th><th>{tr("experience.teamScore")}</th></tr></thead><tbody>{[82,62,null,78,null].map((score,i) => <tr key={i}><td>{tr("experience.member",{n:i+1})}</td><td><span className="ex-badge">{tr(score === null ? "experience.teamHidden" : "experience.teamOpted")}</span></td><td>{score ?? "—"}</td></tr>)}</tbody></table></section></div>}
      {screen === "guardian" && <div className="grid gap-5"><div className="ex-page-heading"><div><p className="ex-eyebrow">{tr("guardian.eyebrow")}</p><h1>{tr("guardian.title")}</h1><p>{tr("guardian.subtitle")}</p></div></div><section className="ex-panel"><span className="ex-badge">{tr("experience.guardianDemoLabel")}</span><blockquote className="my-6 border-l-2 border-accent pl-5 text-base leading-8">{tr("experience.guardianSampleText")}</blockquote><h2 className="text-xl font-medium">{tr("experience.guardianDemoTitle")}</h2><p className="ex-note mt-4">{tr("experience.guardianDemoBody")}</p><Link className="ex-button mt-6" href="/guardian">{tr("guardian.analyze")} ↗</Link><Link className="ex-emergency-link ml-4" href="/ayuda-urgente">{tr("experience.emergency")} ↗</Link></section></div>}
      {screen === "system" && <div className="grid gap-5"><div className="ex-page-heading"><div><p className="ex-eyebrow">Rastro / UI</p><h1>{tr("experience.systemTitle")}</h1><p>{tr("experience.systemBody")}</p></div></div><div className="ex-system-swatches">{["#0a0a0a","#151515","#1d1d1d","#4dfc5f"].map((color) => <div key={color}><i style={{background:color}}/><span>{color}</span></div>)}</div><section className="ex-panel flex flex-wrap justify-around gap-5">{[24,62,88].map((score) => <ScoreRing key={score} score={score} label={tr("experience.score")} size={150}/>)}</section><div className="ex-actions">{["active","pending","attention","completed"].map((state) => <span key={state} className="ex-badge">{tr(`experience.${state}`)}</span>)}</div><section className="ex-panel" aria-label={tr("experience.loading")}><div className="ex-skeleton w-2/3"/><div className="ex-skeleton"/><div className="ex-skeleton w-1/2"/></section><section className="ex-panel"><EmptyState title={tr("experience.emptyTitle")} body={tr("experience.emptyBody")} href="/demo?screen=report" cta={tr("experience.viewReport")}/></section></div>}
    </main>
  </>;
}
