/**
 * Catalogo de sitios que publican o venden datos personales, con el
 * contacto de privacidad y el tramite de baja de cada uno. Es contenido
 * mantenido a mano: nada de esto se inventa en tiempo de ejecucion.
 *
 *   confidence "verified": contacto sacado de la politica de privacidad o
 *   pagina oficial del sitio (fecha en `checked`). "likely": deducido de la
 *   politica general del grupo o de la practica habitual; comprobar al usar.
 *
 * Se usa en tres sitios: cartas (destinatario sin tener que preguntar a
 * Perplexity), informe (etiqueta "sitio conocido" + pasos) y paginas
 * publicas /sitios/[slug] ("como borrar mis datos de X").
 */

export type BrokerKind = "broker" | "people-search" | "business-registry" | "directory" | "phonebook" | "results";

export interface Broker {
  slug: string;
  name: string;
  /** Hosts sin www. Coincidencia por sufijo. */
  hosts: string[];
  kind: BrokerKind;
  /** Pais/ambito principal (ISO) */
  country: "ES" | "US" | "INT";
  /** Que muestra de una persona (ES, lenguaje llano). */
  shows: string;
  /** Correo de privacidad/DPO si existe. */
  email: string | null;
  /** Formulario de baja o pagina de derechos. */
  optOutUrl: string | null;
  privacyUrl: string | null;
  confidence: "verified" | "likely";
  checked: string; // YYYY-MM-DD
  /** Pasos concretos (ES). */
  steps: string[];
  /** Respuesta tipica en dias (orientativo). */
  typicalDays: number | null;
  /** Notas: base legal que alegan, trucos, si piden DNI, etc. */
  notes: string | null;
}

export const BROKERS: Broker[] = [
  {
    slug: "dateas",
    name: "Dateas",
    hosts: ["dateas.com"],
    kind: "people-search",
    country: "ES",
    shows: "Nombre, provincia, edad aproximada y, previo pago, dirección y teléfono sacados de guías y boletines.",
    email: null,
    optOutUrl: "https://www.dateas.com/es/privacidad",
    privacyUrl: "https://www.dateas.com/es/privacidad",
    confidence: "verified",
    checked: "2026-09-13",
    steps: [
      "Copia la URL exacta de la página donde apareces.",
      "Envía la carta de supresión (art. 17) al departamento de protección de datos que indica su política de privacidad; adjunta una imagen legible de tu DNI con todo tapado salvo nombre, apellidos y número.",
      "Guarda el acuse. Tienen un mes para contestar.",
    ],
    typicalDays: 20,
    notes: "El responsable es Plusideas Ltd (Guildford, Reino Unido). Exigen copia de documento de identidad para atender la solicitud. Si el correo de contacto no aparece en la política, usa el formulario de contacto de la web y la dirección postal.",
  },
  {
    slug: "axesor",
    name: "Axesor (Experian)",
    hosts: ["axesor.es", "axesor.com"],
    kind: "business-registry",
    country: "ES",
    shows: "Cargos en empresas (administrador, apoderado), NIF de la empresa, historial mercantil sacado del BORME.",
    email: "dpospain@experian.com",
    optOutUrl: "https://www.axesor.es/información-tratamientos-rgpd",
    privacyUrl: "https://www.axesor.es/política-seguridad-privacidad.aspx",
    confidence: "verified",
    checked: "2026-09-13",
    steps: [
      "Envía la carta a dpospain@experian.com (DPO) con copia a bcatcliente@experian.com, adjuntando copia del DNI.",
      "Indica que te opones al tratamiento por interés legítimo (art. 21) y pides supresión (art. 17) de tus datos como persona física.",
      "Si el dato viene del BORME, pueden alegar fuente pública: pide al menos que dejen de indexarlo en buscadores y que retiren teléfono/dirección.",
    ],
    typicalDays: 30,
    notes: "Tratan datos de directivos por interés legítimo. Dirección postal: Avenida del Conocimiento 16, Edificio I+D Armilla, 18016 Granada.",
  },
  {
    slug: "einforma",
    name: "eInforma (Informa D&B)",
    hosts: ["einforma.com", "informa.es"],
    kind: "business-registry",
    country: "ES",
    shows: "Cargos y vinculaciones con empresas, fecha de nombramiento, a veces domicilio social que coincide con el particular.",
    email: "dpo@informa.es",
    optOutUrl: "https://www.einforma.com/politicas-privacidad",
    privacyUrl: "https://www.einforma.com/politicas-privacidad",
    confidence: "verified",
    checked: "2026-09-13",
    steps: [
      "Escribe a dpo@informa.es (o a clientes@einforma.com con asunto «Proteccion de Datos») con la carta y copia del DNI.",
      "Cita la URL exacta y pide supresión y desindexación.",
      "Si eres autónomo sin sociedad, recuerdales el criterio de la AEPD sobre datos de empresarios autónomos.",
    ],
    typicalDays: 20,
    notes: "Grupo INFORMA D&B. Suelen contestar; a veces solo retiran los datos que no proceden de fuentes oficiales.",
  },
  {
    slug: "infocif",
    name: "Infocif",
    hosts: ["infocif.es", "infocif.com"],
    kind: "business-registry",
    country: "ES",
    shows: "Cargos en empresas y datos mercantiles del BORME; perfiles de directivos indexados en Google.",
    email: null,
    optOutUrl: "https://www.infocif.es/aviso-legal",
    privacyUrl: "https://www.infocif.es/aviso-legal",
    confidence: "likely",
    checked: "2026-09-13",
    steps: [
      "Busca en su aviso legal el correo para el ejercicio de derechos y envía la carta con copia del DNI.",
      "Cita la URL de tu perfil y pide supresión + desindexación.",
      "Sin respuesta en un mes: reclamación AEPD (Rastro te la prepara).",
    ],
    typicalDays: 30,
    notes: "Datos de fuente oficial (BORME). Aun así, la AEPD ha obligado a retirar datos de administradores en varios procedimientos.",
  },
  {
    slug: "empresite",
    name: "Empresite (elEconomista)",
    hosts: ["empresite.eleconomista.es"],
    kind: "business-registry",
    country: "ES",
    shows: "Fichas de empresas y de directivos (nombre, cargo, empresa, provincia).",
    email: null,
    optOutUrl: "https://empresite.eleconomista.es/PORTAL-DIRECTIVOS.html",
    privacyUrl: "https://www.eleconomista.es/política-de-privacidad/index-2018-05-25.php",
    confidence: "likely",
    checked: "2026-09-13",
    steps: [
      "En tu ficha, usa el enlace de «denunciar/informar» si existe; si no, escribe al contacto de privacidad de elEconomista (Editorial Ecoprensa) con la carta.",
      "Adjunta la URL y copia del DNI.",
    ],
    typicalDays: 20,
    notes: "Responsable: Editorial Ecoprensa S.A. Tienen formulario de abuso para datos aportados por usuarios.",
  },
  {
    slug: "guiaempresas-universia",
    name: "Guía Empresas (Universia)",
    hosts: ["guiaempresas.universia.es"],
    kind: "business-registry",
    country: "ES",
    shows: "Listado de empresas con administradores y dirección; muy indexado en Google.",
    email: null,
    optOutUrl: "https://guiaempresas.universia.es/",
    privacyUrl: "https://guiaempresas.universia.es/",
    confidence: "likely",
    checked: "2026-09-13",
    steps: [
      "Localiza el aviso legal/política de privacidad al pie de la página y el correo de derechos.",
      "Envía la carta con la URL y copia del DNI; pide supresión y desindexación.",
    ],
    typicalDays: 30,
    notes: null,
  },
  {
    slug: "infobel",
    name: "Infobel",
    hosts: ["infobel.com"],
    kind: "phonebook",
    country: "INT",
    shows: "Nombre, dirección y teléfono fijo (guías antiguas).",
    email: null,
    optOutUrl: "https://www.infobel.com/es/spain/UpdateData/Index",
    privacyUrl: "https://www.infobel.com/es/spain/privacy",
    confidence: "verified",
    checked: "2026-09-13",
    steps: [
      "Abre el formulario de actualización/baja de Infobel y pide la eliminación de tu registro.",
      "Después, pide a Google la retirada de la URL antigua (Resultados sobre ti) porque la caché tarda en desaparecer.",
    ],
    typicalDays: 10,
    notes: "El dato suele venir del operador telefónico: pide también a tu operador (1004 Movistar, etc.) que no ceda tus datos a guías.",
  },
  {
    slug: "páginas-blancas",
    name: "Páginas Blancas",
    hosts: ["paginasblancas.es", "blancas.paginasamarillas.es"],
    kind: "phonebook",
    country: "ES",
    shows: "Nombre, dirección y teléfono fijo.",
    email: null,
    optOutUrl: "https://www.paginasamarillas.es/",
    privacyUrl: "https://www.paginasamarillas.es/política-privacidad",
    confidence: "likely",
    checked: "2026-09-13",
    steps: [
      "Llama a tu operador y pide que retire tus datos de las guías (el operador es quien los cede).",
      "Envía ademas la carta al contacto de privacidad de Páginas Amarillas/Hibu con la URL.",
    ],
    typicalDays: 30,
    notes: "La última guia impresa fue de 2012; el listado online sigue vivo para fijos antiguos.",
  },
  {
    slug: "cylex",
    name: "Cylex",
    hosts: ["cylex.es", "cylex-espana.es"],
    kind: "directory",
    country: "INT",
    shows: "Fichas de negocios y profesionales con teléfono y dirección, a veces de particulares autónomos.",
    email: "info@cylex-espana.es",
    optOutUrl: "https://www.cylex.es/info/faq.html",
    privacyUrl: "https://www.cylex.es/info/faq.html",
    confidence: "verified",
    checked: "2026-09-13",
    steps: [
      "En tu ficha pulsa «Notificar datos incorrectos» y elige «Eliminar el listado».",
      "Si no responden en unos días, escribe a info@cylex-espana.es con la carta.",
    ],
    typicalDays: 7,
    notes: null,
  },
  {
    slug: "zabasearch",
    name: "ZabaSearch",
    hosts: ["zabasearch.com"],
    kind: "people-search",
    country: "US",
    shows: "Nombre, edad, ciudad, teléfonos, direcciones y familiares (agregados de otros brokers).",
    email: null,
    optOutUrl: "https://www.zabasearch.com/block_records/",
    privacyUrl: "https://www.zabasearch.com/privacy/",
    confidence: "verified",
    checked: "2026-09-13",
    steps: [
      "Abre el formulario de bloqueo de registros, busca tu ficha y solicita el bloqueo.",
      "Confirma el correo que te envian. Suele desaparecer en 24–72 h.",
      "Es la misma empresa que Intelius/PeopleConnect: si apareces en Intelius, usa su centro de supresión.",
    ],
    typicalDays: 3,
    notes: "Formulario propio; no hace falta carta, pero guarda captura de la solicitud.",
  },
  {
    slug: "spokeo",
    name: "Spokeo",
    hosts: ["spokeo.com"],
    kind: "people-search",
    country: "US",
    shows: "Perfil agregado: nombre, edad, direcciones, teléfonos, redes sociales, familiares.",
    email: "privacy@spokeo.com",
    optOutUrl: "https://www.spokeo.com/optout",
    privacyUrl: "https://www.spokeo.com/privacy",
    confidence: "verified",
    checked: "2026-09-13",
    steps: [
      "Copia la URL de tu perfil en Spokeo y pegala en spokeo.com/optout.",
      "Confirma el enlace que llega a tu correo. Se retira en 1–3 días.",
    ],
    typicalDays: 3,
    notes: null,
  },
  {
    slug: "radaris",
    name: "Radaris",
    hosts: ["radaris.com"],
    kind: "people-search",
    country: "US",
    shows: "Nombre, direcciones, teléfonos, familiares, empleos y redes.",
    email: "support@radaris.com",
    optOutUrl: "https://radaris.com/control/privacy",
    privacyUrl: "https://radaris.com/page/privacy",
    confidence: "verified",
    checked: "2026-09-13",
    steps: [
      "Entra en radaris.com/control/privacy, localiza tu perfil y pide su eliminación.",
      "Si te exigen crear cuenta o enviar documento, alternativamente escribe a support@radaris.com con la carta y la URL.",
    ],
    typicalDays: 7,
    notes: "Históricamente pone trabas; la carta con mención al RGPD (art. 3.2) funciona aunque sea empresa de EE. UU.",
  },
  {
    slug: "whitepages",
    name: "Whitepages",
    hosts: ["whitepages.com"],
    kind: "people-search",
    country: "US",
    shows: "Direcciones, teléfonos, edad y familiares.",
    email: "support@whitepages.com",
    optOutUrl: "https://www.whitepages.com/suppression_requests",
    privacyUrl: "https://www.whitepages.com/privacy",
    confidence: "verified",
    checked: "2026-09-13",
    steps: [
      "Pega la URL de tu perfil en whitepages.com/suppression_requests y sigue los pasos (verificación por teléfono).",
      "Si no tienes número de EE. UU., escribe a support@whitepages.com con la carta y la URL.",
    ],
    typicalDays: 3,
    notes: null,
  },
  {
    slug: "truepeoplesearch",
    name: "TruePeopleSearch",
    hosts: ["truepeoplesearch.com"],
    kind: "people-search",
    country: "US",
    shows: "Direcciones, teléfonos, correos y familiares.",
    email: null,
    optOutUrl: "https://www.truepeoplesearch.com/removal",
    privacyUrl: "https://www.truepeoplesearch.com/privacy",
    confidence: "verified",
    checked: "2026-09-13",
    steps: ["Abre truepeoplesearch.com/removal, busca tu registro y pulsa «Remove this record».", "Se elimina en 24–48 h."],
    typicalDays: 2,
    notes: null,
  },
  {
    slug: "fastpeoplesearch",
    name: "FastPeopleSearch",
    hosts: ["fastpeoplesearch.com"],
    kind: "people-search",
    country: "US",
    shows: "Direcciones, teléfonos, correos y familiares.",
    email: null,
    optOutUrl: "https://www.fastpeoplesearch.com/removal",
    privacyUrl: "https://www.fastpeoplesearch.com/privacy",
    confidence: "verified",
    checked: "2026-09-13",
    steps: ["Abre fastpeoplesearch.com/removal, localiza tu registro y solicita la retirada.", "Se elimina en 24–72 h."],
    typicalDays: 3,
    notes: null,
  },
  {
    slug: "beenverified",
    name: "BeenVerified",
    hosts: ["beenverified.com"],
    kind: "people-search",
    country: "US",
    shows: "Informe agregado con direcciones, teléfonos, redes y antecedentes.",
    email: "privacy@beenverified.com",
    optOutUrl: "https://www.beenverified.com/app/optout/search",
    privacyUrl: "https://www.beenverified.com/privacy/",
    confidence: "verified",
    checked: "2026-09-13",
    steps: ["Busca tu ficha en el formulario de opt-out y confirma el correo.", "Misma empresa que PeopleLooker y NeighborWho: se retira de todas."],
    typicalDays: 3,
    notes: null,
  },
  {
    slug: "pipl",
    name: "Pipl",
    hosts: ["pipl.com"],
    kind: "people-search",
    country: "INT",
    shows: "Identidades agregadas para empresas (correos, teléfonos, perfiles).",
    email: "privacy@pipl.com",
    optOutUrl: "https://pipl.com/personal-information-removal-request",
    privacyUrl: "https://pipl.com/privacy",
    confidence: "verified",
    checked: "2026-09-13",
    steps: ["Rellena el formulario de retirada de información personal o escribe a privacy@pipl.com con la carta."],
    typicalDays: 10,
    notes: null,
  },
  {
    slug: "yasni",
    name: "Yasni",
    hosts: ["yasni.com", "yasni.es"],
    kind: "people-search",
    country: "INT",
    shows: "Buscador de personas que agrega resultados de la web bajo tu nombre.",
    email: "support@yasni.com",
    optOutUrl: "https://www.yasni.com/impressum",
    privacyUrl: "https://www.yasni.com/privacy",
    confidence: "likely",
    checked: "2026-09-13",
    steps: ["Escribe a support@yasni.com con la URL de resultados y la carta; pide que bloqueen tu nombre.", "Los resultados son enlaces a otros sitios: pide también la retirada en el origen."],
    typicalDays: 14,
    notes: null,
  },
  {
    slug: "runedia",
    name: "Runedia y clasificaciones deportivas",
    hosts: ["runedia.com", "runedia.mundodeportivo.com"],
    kind: "results",
    country: "ES",
    shows: "Nombre, tiempo, categoría de edad y club en clasificaciones de carreras; confirma tu ciudad.",
    email: null,
    optOutUrl: null,
    privacyUrl: "https://www.mundodeportivo.com/política-privacidad",
    confidence: "likely",
    checked: "2026-09-13",
    steps: [
      "Pide al organizador de la carrera (responsable del tratamiento) que muestre solo el dorsal o retire tu nombre.",
      "Envía la carta también al portal que republica la clasificacion.",
      "En futuras inscripciones, busca la casilla de «no publicar mi nombre en resultados».",
    ],
    typicalDays: 30,
    notes: "Los organizadores suelen alegar interés legítimo/consentimiento en la inscripción; aun así deben atender la oposición (art. 21).",
  },
  {
    slug: "strava",
    name: "Strava",
    hosts: ["strava.com"],
    kind: "directory",
    country: "INT",
    shows: "Rutas con hora y punto de salida (revela dónde vives y a qué hora no estas en casa), fotos y clubes.",
    email: "privacy@strava.com",
    optOutUrl: "https://www.strava.com/settings/privacy",
    privacyUrl: "https://www.strava.com/legal/privacy",
    confidence: "verified",
    checked: "2026-09-13",
    steps: [
      "No hace falta carta: en Ajustes → Controles de privacidad pon perfil y actividades en «Solo seguidores».",
      "Activa «Zonas de privacidad» alrededor de casa y del trabajo y desactiva «Mapa de calor / Flyby».",
      "Si quieres borrar la cuenta entera: Ajustes → Mi cuenta → Eliminar cuenta.",
    ],
    typicalDays: 0,
    notes: "Es tu propia cuenta: lo arreglas tu en dos minutos.",
  },
  {
    slug: "instagram",
    name: "Instagram",
    hosts: ["instagram.com"],
    kind: "directory",
    country: "INT",
    shows: "Perfil, biografía (profesion, ciudad), fotos y ubicaciones etiquetadas.",
    email: null,
    optOutUrl: "https://www.instagram.com/accounts/privacy_and_security/",
    privacyUrl: "https://privacycenter.instagram.com/",
    confidence: "verified",
    checked: "2026-09-13",
    steps: ["Pasa la cuenta a privada (Configuración → Privacidad de la cuenta).", "Quita de la biografía profesion, ciudad y enlaces; revisa las ubicaciones etiquetadas.", "Si alguien ha publicado tus datos sin permiso, usa el formulario de privacidad del Centro de privacidad."],
    typicalDays: 0,
    notes: "Es tu cuenta: sin carta.",
  },
  {
    slug: "linkedin",
    name: "LinkedIn",
    hosts: ["linkedin.com"],
    kind: "directory",
    country: "INT",
    shows: "Empleo actual, empresa, ciudad, correo de contacto (si lo pusiste) y trayectoria.",
    email: null,
    optOutUrl: "https://www.linkedin.com/mypreferences/d/settings/profile-visibility",
    privacyUrl: "https://www.linkedin.com/legal/privacy-policy",
    confidence: "verified",
    checked: "2026-09-13",
    steps: ["Ajustes → Visibilidad → «Visibilidad de tu perfil público»: limita lo que se ve sin iniciar sesion y desactiva la indexación en buscadores.", "Quita el correo y el teléfono de la sección de contacto.", "Si no quieres que la IA sepa dónde trabajas, pon la empresa sin ciudad o usa el sector en vez del nombre."],
    typicalDays: 0,
    notes: "Es tu cuenta: sin carta. Lo que la IA dice de tu empleo suele salir de aquí.",
  },
  {
    slug: "facebook",
    name: "Facebook",
    hosts: ["facebook.com"],
    kind: "directory",
    country: "INT",
    shows: "Perfil, ciudad, trabajo, fotos y amigos, segun tu configuración.",
    email: null,
    optOutUrl: "https://www.facebook.com/settings?tab=privacy",
    privacyUrl: "https://www.facebook.com/privacy/policy/",
    confidence: "verified",
    checked: "2026-09-13",
    steps: ["Configuración → Privacidad → «¿Quién puede ver...?» en Solo amigos; desactiva que los buscadores enlacen tu perfil.", "Revisa «Información» y quita ciudad, trabajo y teléfono."],
    typicalDays: 0,
    notes: "Es tu cuenta: sin carta.",
  },
  {
    slug: "google-resultados-sobre-ti",
    name: "Google (Resultados sobre ti)",
    hosts: ["google.com", "google.es"],
    kind: "results",
    country: "INT",
    shows: "Google no pública tus datos, pero los indexa: teléfono, dirección o correo pueden salir en resultados.",
    email: null,
    optOutUrl: "https://myactivity.google.com/results-about-you",
    privacyUrl: "https://support.google.com/websearch/answer/9673730",
    confidence: "verified",
    checked: "2026-09-13",
    steps: ["Entra en «Resultados sobre ti», añade tu nombre, teléfono, correo y dirección: Google te avisa cuando aparecen y puedes pedir la retirada.", "Para otros datos (fotos, artículos), usa el formulario de derecho al olvido de la UE.", "Recuerda: quitarlo de Google no lo quita del sitio de origen; para eso esta la carta."],
    typicalDays: 7,
    notes: "Gratis. Complementa a Rastro: Google solo cubre su buscador.",
  },
];

/** Devuelve la ficha del sitio para un host (www. y subdominios incluidos) o null. */
export function brokerForHost(host: string): Broker | null {
  const h = host.toLowerCase().replace(/^www\./, "");
  return BROKERS.find((b) => b.hosts.some((bh) => h === bh || h.endsWith("." + bh))) ?? null;
}

export function brokerBySlug(slug: string): Broker | null {
  return BROKERS.find((b) => b.slug === slug) ?? null;
}
