/**
 * Rastreadores conocidos: dominio (sufijo) -> empresa y categoria.
 * Lista corta y mantenida a mano: cubre lo que aparece en la mayoria de webs
 * espanolas. Categoria: "ads" (publicidad), "analytics", "social", "broker"
 * (compraventa de datos / identidad), "cdn" (no rastrea por si mismo).
 */
export const TRACKER_DOMAINS = {
  "doubleclick.net": ["Google", "ads"], "googlesyndication.com": ["Google", "ads"], "googleadservices.com": ["Google", "ads"], "google-analytics.com": ["Google", "analytics"], "googletagmanager.com": ["Google", "analytics"], "adservice.google.com": ["Google", "ads"], "youtube.com": ["Google", "social"],
  "facebook.com": ["Meta", "social"], "facebook.net": ["Meta", "ads"], "instagram.com": ["Meta", "social"], "fbcdn.net": ["Meta", "social"],
  "tiktok.com": ["TikTok", "ads"], "tiktokcdn.com": ["TikTok", "ads"], "byteoversea.com": ["TikTok", "ads"],
  "criteo.com": ["Criteo", "ads"], "criteo.net": ["Criteo", "ads"], "taboola.com": ["Taboola", "ads"], "outbrain.com": ["Outbrain", "ads"], "adnxs.com": ["Xandr (Microsoft)", "ads"], "rubiconproject.com": ["Magnite", "ads"], "pubmatic.com": ["PubMatic", "ads"], "openx.net": ["OpenX", "ads"], "casalemedia.com": ["Index Exchange", "ads"], "smartadserver.com": ["Equativ", "ads"], "adform.net": ["Adform", "ads"], "teads.tv": ["Teads", "ads"], "amazon-adsystem.com": ["Amazon", "ads"], "bing.com": ["Microsoft", "ads"], "clarity.ms": ["Microsoft", "analytics"], "linkedin.com": ["LinkedIn (Microsoft)", "social"], "licdn.com": ["LinkedIn (Microsoft)", "social"], "ads-twitter.com": ["X", "ads"], "twitter.com": ["X", "social"], "t.co": ["X", "social"], "pinterest.com": ["Pinterest", "social"], "pinimg.com": ["Pinterest", "social"], "snapchat.com": ["Snap", "ads"], "sc-static.net": ["Snap", "ads"],
  "hotjar.com": ["Hotjar", "analytics"], "hotjar.io": ["Hotjar", "analytics"], "mouseflow.com": ["Mouseflow", "analytics"], "fullstory.com": ["FullStory", "analytics"], "segment.com": ["Segment (Twilio)", "analytics"], "segment.io": ["Segment (Twilio)", "analytics"], "mixpanel.com": ["Mixpanel", "analytics"], "amplitude.com": ["Amplitude", "analytics"], "hubspot.com": ["HubSpot", "analytics"], "hs-analytics.net": ["HubSpot", "analytics"], "hs-scripts.com": ["HubSpot", "analytics"], "matomo.cloud": ["Matomo", "analytics"], "yandex.ru": ["Yandex", "analytics"], "mc.yandex.ru": ["Yandex", "analytics"], "newrelic.com": ["New Relic", "analytics"], "nr-data.net": ["New Relic", "analytics"], "sentry.io": ["Sentry", "analytics"], "optimizely.com": ["Optimizely", "analytics"], "comscore.com": ["Comscore", "analytics"], "scorecardresearch.com": ["Comscore", "analytics"], "chartbeat.com": ["Chartbeat", "analytics"], "chartbeat.net": ["Chartbeat", "analytics"],
  "liveramp.com": ["LiveRamp", "broker"], "rlcdn.com": ["LiveRamp", "broker"], "agkn.com": ["Neustar", "broker"], "bluekai.com": ["Oracle BlueKai", "broker"], "krxd.net": ["Salesforce Krux", "broker"], "demdex.net": ["Adobe Audience Manager", "broker"], "everesttech.net": ["Adobe", "ads"], "exelator.com": ["Nielsen", "broker"], "crwdcntrl.net": ["Lotame", "broker"], "tapad.com": ["Tapad (Experian)", "broker"], "id5-sync.com": ["ID5", "broker"], "adsrvr.org": ["The Trade Desk", "ads"], "quantserve.com": ["Quantcast", "broker"], "quantcount.com": ["Quantcast", "broker"], "zeotap.com": ["Zeotap", "broker"], "eyeota.net": ["Eyeota", "broker"],
  "cloudflare.com": ["Cloudflare", "cdn"], "cloudflareinsights.com": ["Cloudflare", "analytics"], "jsdelivr.net": ["jsDelivr", "cdn"], "gstatic.com": ["Google", "cdn"], "googleapis.com": ["Google", "cdn"], "cloudfront.net": ["Amazon CloudFront", "cdn"], "akamaihd.net": ["Akamai", "cdn"], "unpkg.com": ["unpkg", "cdn"],
};

/** Nombres de cookie conocidos (prefijo) -> [empresa, categoria]. "necessary" = sesion, seguridad o consentimiento. */
export const COOKIE_NAMES = [
  ["_ga", "Google", "analytics"], ["_ga_", "Google", "analytics"], ["_gid", "Google", "analytics"], ["_gat", "Google", "analytics"], ["_gcl_", "Google", "ads"], ["__gads", "Google", "ads"], ["__gpi", "Google", "ads"], ["IDE", "Google", "ads"], ["test_cookie", "Google", "ads"], ["NID", "Google", "ads"], ["DSID", "Google", "ads"],
  ["_fbp", "Meta", "ads"], ["_fbc", "Meta", "ads"], ["fr", "Meta", "ads"], ["datr", "Meta", "social"],
  ["_ttp", "TikTok", "ads"], ["_tt_enable_cookie", "TikTok", "ads"], ["ttwid", "TikTok", "ads"],
  ["_uetsid", "Microsoft", "ads"], ["_uetvid", "Microsoft", "ads"], ["MUID", "Microsoft", "ads"], ["_clck", "Microsoft", "analytics"], ["_clsk", "Microsoft", "analytics"],
  ["li_", "LinkedIn (Microsoft)", "ads"], ["bcookie", "LinkedIn (Microsoft)", "social"], ["lidc", "LinkedIn (Microsoft)", "social"], ["UserMatchHistory", "LinkedIn (Microsoft)", "ads"], ["AnalyticsSyncHistory", "LinkedIn (Microsoft)", "ads"],
  ["_pin_unauth", "Pinterest", "ads"], ["_pinterest_", "Pinterest", "ads"], ["_scid", "Snap", "ads"], ["sc_at", "Snap", "ads"], ["cto_", "Criteo", "ads"], ["uid", "Criteo", "ads"], ["t_gid", "Taboola", "ads"], ["obuid", "Outbrain", "ads"], ["uuid2", "Xandr (Microsoft)", "ads"], ["anj", "Xandr (Microsoft)", "ads"], ["TDID", "The Trade Desk", "ads"], ["ad-id", "Amazon", "ads"], ["ad-privacy", "Amazon", "ads"],
  ["_hj", "Hotjar", "analytics"], ["hubspotutk", "HubSpot", "analytics"], ["__hs", "HubSpot", "analytics"], ["mp_", "Mixpanel", "analytics"], ["amplitude_id", "Amplitude", "analytics"], ["AMP_", "Amplitude", "analytics"], ["ajs_", "Segment (Twilio)", "analytics"], ["_pk_", "Matomo", "analytics"], ["_ym_", "Yandex", "analytics"], ["optimizely", "Optimizely", "analytics"], ["_cb", "Chartbeat", "analytics"], ["_chartbeat", "Chartbeat", "analytics"],
  ["demdex", "Adobe Audience Manager", "broker"], ["dpm", "Adobe Audience Manager", "broker"], ["rlas3", "LiveRamp", "broker"], ["pxrc", "LiveRamp", "broker"], ["bku", "Oracle BlueKai", "broker"], ["_kuid_", "Salesforce Krux", "broker"], ["_cc_", "Lotame", "broker"], ["mc", "Quantcast", "broker"], ["__qca", "Quantcast", "broker"], ["id5", "ID5", "broker"],
  ["OptanonConsent", "OneTrust", "necessary"], ["OptanonAlertBoxClosed", "OneTrust", "necessary"], ["CookieConsent", "Cookiebot", "necessary"], ["euconsent", "CMP (TCF)", "necessary"], ["didomi_token", "Didomi", "necessary"], ["cookieyes-consent", "CookieYes", "necessary"], ["cmplz_", "Complianz", "necessary"], ["cookielawinfo", "CookieLaw", "necessary"], ["borlabs-cookie", "Borlabs", "necessary"], ["usprivacy", "CMP (US)", "necessary"],
  ["PHPSESSID", "", "necessary"], ["JSESSIONID", "", "necessary"], ["ASP.NET_SessionId", "", "necessary"], ["connect.sid", "", "necessary"], ["session", "", "necessary"], ["sessionid", "", "necessary"], ["csrftoken", "", "necessary"], ["XSRF-TOKEN", "", "necessary"], ["_csrf", "", "necessary"], ["__cf_bm", "Cloudflare", "necessary"], ["cf_clearance", "Cloudflare", "necessary"], ["__Host-", "", "necessary"], ["__Secure-", "", "necessary"], ["wordpress_", "WordPress", "necessary"], ["wp-settings", "WordPress", "necessary"], ["cart", "", "necessary"], ["woocommerce_", "WooCommerce", "necessary"], ["rastro_", "Rastro", "necessary"],
];

/** Textos de botones de "rechazar" de los banners de cookies (en minusculas). */
export const REJECT_TEXTS = ["rechazar todo", "rechazar todas", "rechazar", "rechazarlas", "solo necesarias", "sólo necesarias", "solo las necesarias", "solo esenciales", "continuar sin aceptar", "no acepto", "denegar", "reject all", "reject", "decline", "deny", "only necessary", "necessary only", "use necessary cookies only", "refuse", "refuser", "tout refuser", "alle ablehnen", "ablehnen"];

// Dominios que corta el bloqueo opcional: publicidad y comercio de datos. Fuera quedan los que tambien sirven contenido
// o inicio de sesion (videos de TikTok, "Entrar con Facebook", mapas de Bing): bloquearlos rompe webs.
const NO_BLOCK = new Set(["tiktok.com", "tiktokcdn.com", "byteoversea.com", "bing.com", "snapchat.com", "sc-static.net", "facebook.net"]);
export function blockedDomains() {
  return Object.entries(TRACKER_DOMAINS).filter(([domain, [, category]]) => (category === "ads" || category === "broker") && !NO_BLOCK.has(domain)).map(([domain]) => domain).sort();
}
